AWSTemplateFormatVersion: "2010-09-09"
Description: >
  S3 bucket for e-bank user data.

Parameters:
  StackName:
    Type: String
    Description: Stack name for unique resource naming
    Default: eBankStack

Resources:
  UserDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "e-bank-user-data-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled

Outputs:
  UserDataBucketName:
    Description: S3 bucket name for user JSON objects
    Value: !Ref UserDataBucket
    Export:
      Name: !Sub "${StackName}-UserDataBucket"

  UserDataBucketArn:
    Description: S3 bucket ARN for user JSON objects
    Value: !GetAtt UserDataBucket.Arn
    Export:
      Name: !Sub "${StackName}-UserDataBucketArn"
